services:
  - type: web
    name: bezubaan-ml
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: API_KEY
        value: bezubaan_secret_0107